In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import ast
import json

Se usará una forma similar a las usadas en Movies_ETL.ipynb, utilizando la librería `ast` para desanidar las columnas y poder separar los datos de actores y miembros del crew en dos datasets, `actors.csv` y `crew.csv`. Estos serviran para las funciones de la API donde debe retornarse a los actores junto con datos de las peliculas donde participaron, asi como el retorno de los directores y las peliculas que dirigieron.

In [ ]:
df = pd.read_csv("credits.csv") # el archivo credits.csv lo elimine luego de las transformaciones debido a su tamaño
df

In [16]:
dataframe_from_col1 = pd.DataFrame(columns=['cast_id','character','credit_id','actor_gender','actor_id','actor_name','order','profile_path'])

for value in df["cast"]:
    if pd.notna(value):  # Check if the value is not NaN
        data = ast.literal_eval(value)
        if isinstance(data, list) and len(data) > 0:
            cast_id = [item['cast_id'] for item in data]
            character = [item['character'] for item in data]
            credit_id = [item['credit_id'] for item in data]
            actor_gender = [item['gender'] for item in data]
            actor_id = [item['id'] for item in data]
            actor_name = [item['name'] for item in data]
            order = [item['order'] for item in data]
            profile_path = [item['profile_path'] for item in data]
            dataframe_from_col1.loc[len(dataframe_from_col1)] = [
                cast_id,
                character,
                credit_id,
                actor_gender,
                actor_id,
                actor_name,
                order,
                profile_path
            ]
        else:
            dataframe_from_col1.loc[len(dataframe_from_col1)] = [None, None,None, None,None, None,None,None]
    else:
        dataframe_from_col1.loc[len(dataframe_from_col1)] = [None, None,None, None,None, None,None,None]

dataframe_from_col1.head(5)

,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path
0,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","[Woody (voice), Buzz Lightyear (voice), Mr. Po...","[52fe4284c3a36847f8024f95, 52fe4284c3a36847f80...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[/pQFoyx7rp09CJTAb932F2g8Nlho.jpg, /uX2xVf6pMm..."
1,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","[Alan Parrish, Samuel Alan Parrish / Van Pelt,...","[52fe44bfc3a36847f80a7c73, 52fe44bfc3a36847f80...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[/sojtJyIV3lkUeThD7A2oHNm8183.jpg, /7il5D76vx6..."
2,"[2, 3, 4, 5, 6, 9, 10]","[Max Goldman, John Gustafson, Ariel Gustafson,...","[52fe466a9251416c75077a8d, 52fe466a9251416c750...","[2, 2, 1, 1, 1, 2, 2]","[6837, 3151, 13567, 16757, 589, 16523, 7166]","[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...","[0, 1, 2, 3, 4, 5, 6]","[/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg, /chZmNRYMtq..."
3,"[1, 2, 3, 4, 5, 6, 8, 10, 20, 21]","[Savannah 'Vannah' Jackson, Bernadine 'Bernie'...","[52fe44779251416c91011aad, 52fe44779251416c910...","[1, 1, 1, 1, 2, 2, 2, 2, 2, 2]","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","[Whitney Houston, Angela Bassett, Loretta Devi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[/69ouDnXnmklYPr4sMJXWKYz81AL.jpg, /tHkgSzhEuJ..."
4,"[1, 2, 3, 4, 13, 14, 15, 16, 17, 18, 19, 20]","[George Banks, Nina Banks, Franck Eggelhoffer,...","[52fe44959251416c75039eb9, 52fe44959251416c750...","[2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1]","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","[Steve Martin, Diane Keaton, Martin Short, Kim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]","[/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg, /fzgUMnbOkx..."

In [20]:
result_dataframe = df.join(dataframe_from_col1)
result_dataframe.head(5)

,cast,crew,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","[Woody (voice), Buzz Lightyear (voice), Mr. Po...","[52fe4284c3a36847f8024f95, 52fe4284c3a36847f80...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[/pQFoyx7rp09CJTAb932F2g8Nlho.jpg, /uX2xVf6pMm..."
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","[Alan Parrish, Samuel Alan Parrish / Van Pelt,...","[52fe44bfc3a36847f80a7c73, 52fe44bfc3a36847f80...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[/sojtJyIV3lkUeThD7A2oHNm8183.jpg, /7il5D76vx6..."
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602,"[2, 3, 4, 5, 6, 9, 10]","[Max Goldman, John Gustafson, Ariel Gustafson,...","[52fe466a9251416c75077a8d, 52fe466a9251416c750...","[2, 2, 1, 1, 1, 2, 2]","[6837, 3151, 13567, 16757, 589, 16523, 7166]","[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...","[0, 1, 2, 3, 4, 5, 6]","[/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg, /chZmNRYMtq..."
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357,"[1, 2, 3, 4, 5, 6, 8, 10, 20, 21]","[Savannah 'Vannah' Jackson, Bernadine 'Bernie'...","[52fe44779251416c91011aad, 52fe44779251416c910...","[1, 1, 1, 1, 2, 2, 2, 2, 2, 2]","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","[Whitney Houston, Angela Bassett, Loretta Devi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[/69ouDnXnmklYPr4sMJXWKYz81AL.jpg, /tHkgSzhEuJ..."
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862,"[1, 2, 3, 4, 13, 14, 15, 16, 17, 18, 19, 20]","[George Banks, Nina Banks, Franck Eggelhoffer,...","[52fe44959251416c75039eb9, 52fe44959251416c750...","[2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1]","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","[Steve Martin, Diane Keaton, Martin Short, Kim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]","[/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg, /fzgUMnbOkx..."

In [21]:
dataframe_from_col2 = pd.DataFrame(columns=['crew_credit_id','crew_department','crew_gender','crew_id','crew_job','crew_name','crew_profile_path'])

for value in df["crew"]:
    if pd.notna(value):  # Check if the value is not NaN
        data = ast.literal_eval(value)
        if isinstance(data, list) and len(data) > 0:
            crew_credit_id = [item['credit_id'] for item in data]
            crew_department = [item['department'] for item in data]
            crew_gender = [item['gender'] for item in data]
            crew_id = [item['id'] for item in data]
            crew_job = [item['job'] for item in data]
            crew_name = [item['name'] for item in data]
            crew_profile_path = [item['profile_path'] for item in data]
            dataframe_from_col2.loc[len(dataframe_from_col2)] = [
                crew_credit_id,
                crew_department,
                crew_gender,
                crew_id,
                crew_job,
                crew_name,
                crew_profile_path
            ]
        else:
            dataframe_from_col2.loc[len(dataframe_from_col2)] = [None, None,None, None,None, None,None]
    else:
        dataframe_from_col2.loc[len(dataframe_from_col2)] = [None, None,None, None,None, None,None]

dataframe_from_col2.head(5)

,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,"[52fe4284c3a36847f8024f49, 52fe4284c3a36847f80...","[Directing, Writing, Writing, Writing, Writing...","[2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, ...","[7879, 12891, 7, 12892, 12893, 12894, 12895, 1...","[Director, Screenplay, Screenplay, Screenplay,...","[John Lasseter, Joss Whedon, Andrew Stanton, J...","[/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg, /dTiVsuaTVT..."
1,"[52fe44bfc3a36847f80a7cd1, 52fe44bfc3a36847f80...","[Production, Writing, Sound, Directing, Editin...","[2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[511, 876, 1729, 4945, 4951, 4952, 8023, 9967,...","[Executive Producer, Screenplay, Original Musi...","[Larry J. Franco, Jonathan Hensleigh, James Ho...","[None, /l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg, /oLOt..."
2,"[52fe466a9251416c75077a89, 52fe466b9251416c750...","[Directing, Writing, Writing, Crew]","[2, 2, 2, 2]","[26502, 16837, 16837, 1551320]","[Director, Characters, Writer, Sound Recordist]","[Howard Deutch, Mark Steven Johnson, Mark Stev...","[/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg, /6trChNn3o2..."
3,"[52fe44779251416c91011acb, 52fe44779251416c910...","[Directing, Writing, Production, Production, P...","[2, 0, 0, 2, 1, 0, 0, 0, 2, 0]","[2178, 5144, 5144, 21968, 70592, 111118, 11111...","[Director, Screenplay, Producer, Producer, Pro...","[Forest Whitaker, Ronald Bass, Ronald Bass, Ez...","[/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg, None, None,..."
4,"[52fe44959251416c75039ed7, 52fe44959251416c750...","[Sound, Camera, Writing, Production, Writing, ...","[2, 2, 1, 1, 2, 2, 2]","[37, 5506, 17698, 17698, 26160, 56106, 68755]","[Original Music Composer, Director of Photogra...","[Alan Silvestri, Elliot Davis, Nancy Meyers, N...","[/chEsfnDEtRmv1bfOaNAoVEzhCc6.jpg, None, /nMPH..."

In [22]:
result_dataframe = result_dataframe.join(dataframe_from_col2)
result_dataframe.head(5)

,cast,crew,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","[Woody (voice), Buzz Lightyear (voice), Mr. Po...","[52fe4284c3a36847f8024f95, 52fe4284c3a36847f80...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[/pQFoyx7rp09CJTAb932F2g8Nlho.jpg, /uX2xVf6pMm...","[52fe4284c3a36847f8024f49, 52fe4284c3a36847f80...","[Directing, Writing, Writing, Writing, Writing...","[2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, ...","[7879, 12891, 7, 12892, 12893, 12894, 12895, 1...","[Director, Screenplay, Screenplay, Screenplay,...","[John Lasseter, Joss Whedon, Andrew Stanton, J...","[/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg, /dTiVsuaTVT..."
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","[Alan Parrish, Samuel Alan Parrish / Van Pelt,...","[52fe44bfc3a36847f80a7c73, 52fe44bfc3a36847f80...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[/sojtJyIV3lkUeThD7A2oHNm8183.jpg, /7il5D76vx6...","[52fe44bfc3a36847f80a7cd1, 52fe44bfc3a36847f80...","[Production, Writing, Sound, Directing, Editin...","[2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[511, 876, 1729, 4945, 4951, 4952, 8023, 9967,...","[Executive Producer, Screenplay, Original Musi...","[Larry J. Franco, Jonathan Hensleigh, James Ho...","[None, /l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg, /oLOt..."
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602,"[2, 3, 4, 5, 6, 9, 10]","[Max Goldman, John Gustafson, Ariel Gustafson,...","[52fe466a9251416c75077a8d, 52fe466a9251416c750...","[2, 2, 1, 1, 1, 2, 2]","[6837, 3151, 13567, 16757, 589, 16523, 7166]","[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...","[0, 1, 2, 3, 4, 5, 6]","[/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg, /chZmNRYMtq...","[52fe466a9251416c75077a89, 52fe466b9251416c750...","[Directing, Writing, Writing, Crew]","[2, 2, 2, 2]","[26502, 16837, 16837, 1551320]","[Director, Characters, Writer, Sound Recordist]","[Howard Deutch, Mark Steven Johnson, Mark Stev...","[/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg, /6trChNn3o2..."
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357,"[1, 2, 3, 4, 5, 6, 8, 10, 20, 21]","[Savannah 'Vannah' Jackson, Bernadine 'Bernie'...","[52fe44779251416c91011aad, 52fe44779251416c910...","[1, 1, 1, 1, 2, 2, 2, 2, 2, 2]","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","[Whitney Houston, Angela Bassett, Loretta Devi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[/69ouDnXnmklYPr4sMJXWKYz81AL.jpg, /tHkgSzhEuJ...","[52fe44779251416c91011acb, 52fe44779251416c910...","[Directing, Writing, Production, Production, P...","[2, 0, 0, 2, 1, 0, 0, 0, 2, 0]","[2178, 5144, 5144, 21968, 70592, 111118, 11111...","[Director, Screenplay, Producer, Producer, Pro...","[Forest Whitaker, Ronald Bass, Ronald Bass, Ez...","[/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg, None, None,..."
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862,"[1, 2, 3, 4, 13, 14, 15, 16, 17, 18, 19, 20]","[George Banks, Nina Banks, Franck Eggelhoffer,...","[52fe44959251416c75039eb9, 52fe44959251416c750...","[2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1]","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","[Steve Martin, Diane Keaton, Martin Short, Kim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]","[/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg, /fzgUMnbOkx...","[52fe44959251416c75039ed7, 52fe44959251416c750...","[Sound, Camera, Writing, Production, Writing, ...","[2, 2, 1, 1, 2, 2, 2]","[37, 5506, 17698, 17698, 26160, 56106, 68755]","[Original Music Composer, Director of Photogra...","[Alan Silvestri, Elliot Davis, Nancy Meyers, N...","[/chEsfnDEtRmv1bfOaNAoVEzhCc6.jpg, None, /nMPH..."

In [23]:
result_dataframe.drop(columns=["cast","crew"],axis=1,inplace=True)
result_dataframe.head(5)

,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,862,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","[Woody (voice), Buzz Lightyear (voice), Mr. Po...","[52fe4284c3a36847f8024f95, 52fe4284c3a36847f80...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[/pQFoyx7rp09CJTAb932F2g8Nlho.jpg, /uX2xVf6pMm...","[52fe4284c3a36847f8024f49, 52fe4284c3a36847f80...","[Directing, Writing, Writing, Writing, Writing...","[2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, ...","[7879, 12891, 7, 12892, 12893, 12894, 12895, 1...","[Director, Screenplay, Screenplay, Screenplay,...","[John Lasseter, Joss Whedon, Andrew Stanton, J...","[/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg, /dTiVsuaTVT..."
1,8844,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","[Alan Parrish, Samuel Alan Parrish / Van Pelt,...","[52fe44bfc3a36847f80a7c73, 52fe44bfc3a36847f80...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[/sojtJyIV3lkUeThD7A2oHNm8183.jpg, /7il5D76vx6...","[52fe44bfc3a36847f80a7cd1, 52fe44bfc3a36847f80...","[Production, Writing, Sound, Directing, Editin...","[2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[511, 876, 1729, 4945, 4951, 4952, 8023, 9967,...","[Executive Producer, Screenplay, Original Musi...","[Larry J. Franco, Jonathan Hensleigh, James Ho...","[None, /l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg, /oLOt..."
2,15602,"[2, 3, 4, 5, 6, 9, 10]","[Max Goldman, John Gustafson, Ariel Gustafson,...","[52fe466a9251416c75077a8d, 52fe466a9251416c750...","[2, 2, 1, 1, 1, 2, 2]","[6837, 3151, 13567, 16757, 589, 16523, 7166]","[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...","[0, 1, 2, 3, 4, 5, 6]","[/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg, /chZmNRYMtq...","[52fe466a9251416c75077a89, 52fe466b9251416c750...","[Directing, Writing, Writing, Crew]","[2, 2, 2, 2]","[26502, 16837, 16837, 1551320]","[Director, Characters, Writer, Sound Recordist]","[Howard Deutch, Mark Steven Johnson, Mark Stev...","[/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg, /6trChNn3o2..."
3,31357,"[1, 2, 3, 4, 5, 6, 8, 10, 20, 21]","[Savannah 'Vannah' Jackson, Bernadine 'Bernie'...","[52fe44779251416c91011aad, 52fe44779251416c910...","[1, 1, 1, 1, 2, 2, 2, 2, 2, 2]","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","[Whitney Houston, Angela Bassett, Loretta Devi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[/69ouDnXnmklYPr4sMJXWKYz81AL.jpg, /tHkgSzhEuJ...","[52fe44779251416c91011acb, 52fe44779251416c910...","[Directing, Writing, Production, Production, P...","[2, 0, 0, 2, 1, 0, 0, 0, 2, 0]","[2178, 5144, 5144, 21968, 70592, 111118, 11111...","[Director, Screenplay, Producer, Producer, Pro...","[Forest Whitaker, Ronald Bass, Ronald Bass, Ez...","[/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg, None, None,..."
4,11862,"[1, 2, 3, 4, 13, 14, 15, 16, 17, 18, 19, 20]","[George Banks, Nina Banks, Franck Eggelhoffer,...","[52fe44959251416c75039eb9, 52fe44959251416c750...","[2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1]","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","[Steve Martin, Diane Keaton, Martin Short, Kim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]","[/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg, /fzgUMnbOkx...","[52fe44959251416c75039ed7, 52fe44959251416c750...","[Sound, Camera, Writing, Production, Writing, ...","[2, 2, 1, 1, 2, 2, 2]","[37, 5506, 17698, 17698, 26160, 56106, 68755]","[Original Music Composer, Director of Photogra...","[Alan Silvestri, Elliot Davis, Nancy Meyers, N...","[/chEsfnDEtRmv1bfOaNAoVEzhCc6.jpg, None, /nMPH..."

In [32]:
#result_dataframe.to_csv("credits_unnested.csv", index=False, compression='gzip')

In [2]:
compressed_df = pd.read_csv("credits_unnested.csv",compression='gzip')
compressed_df.head(2)

,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,862,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","['Woody (voice)', 'Buzz Lightyear (voice)', 'M...","['52fe4284c3a36847f8024f95', '52fe4284c3a36847...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","['/pQFoyx7rp09CJTAb932F2g8Nlho.jpg', '/uX2xVf6...","['52fe4284c3a36847f8024f49', '52fe4284c3a36847...","['Directing', 'Writing', 'Writing', 'Writing',...","[2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, ...","[7879, 12891, 7, 12892, 12893, 12894, 12895, 1...","['Director', 'Screenplay', 'Screenplay', 'Scre...","['John Lasseter', 'Joss Whedon', 'Andrew Stant...","['/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg', '/dTiVsua..."
1,8844,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","['Alan Parrish', 'Samuel Alan Parrish / Van Pe...","['52fe44bfc3a36847f80a7c73', '52fe44bfc3a36847...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","['Robin Williams', 'Jonathan Hyde', 'Kirsten D...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","['/sojtJyIV3lkUeThD7A2oHNm8183.jpg', '/7il5D76...","['52fe44bfc3a36847f80a7cd1', '52fe44bfc3a36847...","['Production', 'Writing', 'Sound', 'Directing'...","[2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[511, 876, 1729, 4945, 4951, 4952, 8023, 9967,...","['Executive Producer', 'Screenplay', 'Original...","['Larry J. Franco', 'Jonathan Hensleigh', 'Jam...","[None, '/l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg', '/o..."

Para poder desanidar cada columna se usará la función `explode()` de pandas. Pero se debe primero aplicar una `lambda` a cada columna que se quiere desanidar

In [27]:
df = compressed_df.copy()
for item in df.columns:
  if item != 'id':
    df[item] = df[item].apply(lambda x: ast.literal_eval(x) if not pd.isna(x) else [])
df.head()

,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,862,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","[Woody (voice), Buzz Lightyear (voice), Mr. Po...","[52fe4284c3a36847f8024f95, 52fe4284c3a36847f80...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[/pQFoyx7rp09CJTAb932F2g8Nlho.jpg, /uX2xVf6pMm...","[52fe4284c3a36847f8024f49, 52fe4284c3a36847f80...","[Directing, Writing, Writing, Writing, Writing...","[2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, ...","[7879, 12891, 7, 12892, 12893, 12894, 12895, 1...","[Director, Screenplay, Screenplay, Screenplay,...","[John Lasseter, Joss Whedon, Andrew Stanton, J...","[/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg, /dTiVsuaTVT..."
1,8844,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","[Alan Parrish, Samuel Alan Parrish / Van Pelt,...","[52fe44bfc3a36847f80a7c73, 52fe44bfc3a36847f80...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[/sojtJyIV3lkUeThD7A2oHNm8183.jpg, /7il5D76vx6...","[52fe44bfc3a36847f80a7cd1, 52fe44bfc3a36847f80...","[Production, Writing, Sound, Directing, Editin...","[2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[511, 876, 1729, 4945, 4951, 4952, 8023, 9967,...","[Executive Producer, Screenplay, Original Musi...","[Larry J. Franco, Jonathan Hensleigh, James Ho...","[None, /l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg, /oLOt..."
2,15602,"[2, 3, 4, 5, 6, 9, 10]","[Max Goldman, John Gustafson, Ariel Gustafson,...","[52fe466a9251416c75077a8d, 52fe466a9251416c750...","[2, 2, 1, 1, 1, 2, 2]","[6837, 3151, 13567, 16757, 589, 16523, 7166]","[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...","[0, 1, 2, 3, 4, 5, 6]","[/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg, /chZmNRYMtq...","[52fe466a9251416c75077a89, 52fe466b9251416c750...","[Directing, Writing, Writing, Crew]","[2, 2, 2, 2]","[26502, 16837, 16837, 1551320]","[Director, Characters, Writer, Sound Recordist]","[Howard Deutch, Mark Steven Johnson, Mark Stev...","[/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg, /6trChNn3o2..."
3,31357,"[1, 2, 3, 4, 5, 6, 8, 10, 20, 21]","[Savannah 'Vannah' Jackson, Bernadine 'Bernie'...","[52fe44779251416c91011aad, 52fe44779251416c910...","[1, 1, 1, 1, 2, 2, 2, 2, 2, 2]","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","[Whitney Houston, Angela Bassett, Loretta Devi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[/69ouDnXnmklYPr4sMJXWKYz81AL.jpg, /tHkgSzhEuJ...","[52fe44779251416c91011acb, 52fe44779251416c910...","[Directing, Writing, Production, Production, P...","[2, 0, 0, 2, 1, 0, 0, 0, 2, 0]","[2178, 5144, 5144, 21968, 70592, 111118, 11111...","[Director, Screenplay, Producer, Producer, Pro...","[Forest Whitaker, Ronald Bass, Ronald Bass, Ez...","[/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg, None, None,..."
4,11862,"[1, 2, 3, 4, 13, 14, 15, 16, 17, 18, 19, 20]","[George Banks, Nina Banks, Franck Eggelhoffer,...","[52fe44959251416c75039eb9, 52fe44959251416c750...","[2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1]","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","[Steve Martin, Diane Keaton, Martin Short, Kim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]","[/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg, /fzgUMnbOkx...","[52fe44959251416c75039ed7, 52fe44959251416c750...","[Sound, Camera, Writing, Production, Writing, ...","[2, 2, 1, 1, 2, 2, 2]","[37, 5506, 17698, 17698, 26160, 56106, 68755]","[Original Music Composer, Director of Photogra...","[Alan Silvestri, Elliot Davis, Nancy Meyers, N...","[/chEsfnDEtRmv1bfOaNAoVEzhCc6.jpg, None, /nMPH..."

Ahora que se convirtieron a listas usando `ast.list_eval`, se debe hacer un `explode` de cada columna como sigue

In [28]:
df.columns
['id', 'cast_id', 'character', 'credit_id', 'actor_gender', 'actor_id',
       'actor_name', 'order', 'profile_path', 'crew_credit_id',
       'crew_department', 'crew_gender', 'crew_id', 'crew_job', 'crew_name',
       'crew_profile_path'],

Index(['id', 'cast_id', 'character', 'credit_id', 'actor_gender', 'actor_id',
       'actor_name', 'order', 'profile_path', 'crew_credit_id',
       'crew_department', 'crew_gender', 'crew_id', 'crew_job', 'crew_name',
       'crew_profile_path'],
      dtype='object')

In [37]:
cast_id = df[["id","cast_id"]].explode("cast_id").reset_index(drop=True)
character= df[["id","character"]].explode("character").reset_index(drop=True)
credit_id= df[["id","credit_id"]].explode("credit_id").reset_index(drop=True)
actor_gender= df[["id","actor_gender"]].explode("actor_gender").reset_index(drop=True)
actor_id= df[["id","actor_id"]].explode("actor_id").reset_index(drop=True)
actor_name= df[["id","actor_name"]].explode("actor_name").reset_index(drop=True)
order= df[["id","order"]].explode("order").reset_index(drop=True)
profile_path= df[["id","profile_path"]].explode("profile_path").reset_index(drop=True)
crew_credit_id= df[["id","crew_credit_id"]].explode("crew_credit_id").reset_index(drop=True)
crew_department= df[["id","crew_department"]].explode("crew_department").reset_index(drop=True)
crew_gender= df[["id","crew_gender"]].explode("crew_gender").reset_index(drop=True)
crew_id= df[["id","crew_id"]].explode("crew_id").reset_index(drop=True)
crew_job= df[["id","crew_job"]].explode("crew_job").reset_index(drop=True)
crew_name= df[["id","crew_name"]].explode("crew_name").reset_index(drop=True)
crew_profile_path= df[["id","crew_profile_path"]].explode("crew_profile_path").reset_index(drop=True)

In [48]:
new_df = cast_id
new_df['character'] = character["character"]
new_df['credit_id'] = credit_id["credit_id"]
new_df['actor_gender'] = actor_gender["actor_gender"]
new_df['actor_id'] = actor_id["actor_id"]
new_df['actor_name'] = actor_name["actor_name"]
new_df['order'] = order["order"]
new_df['profile_path'] = profile_path["profile_path"]
new_df['crew_credit_id'] = crew_credit_id["crew_credit_id"]
new_df['crew_department'] = crew_department["crew_department"]
new_df['crew_gender'] = crew_gender["crew_gender"]
new_df['crew_id'] = crew_id["crew_id"]
new_df['crew_job'] = crew_job["crew_job"]
new_df['crew_name'] = crew_name["crew_name"]
new_df['crew_profile_path'] = crew_profile_path["crew_profile_path"]
new_df.head()

,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,862,14,Woody (voice),52fe4284c3a36847f8024f95,2,31,Tom Hanks,0,/pQFoyx7rp09CJTAb932F2g8Nlho.jpg,52fe4284c3a36847f8024f49,Directing,2,7879,Director,John Lasseter,/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg
1,862,15,Buzz Lightyear (voice),52fe4284c3a36847f8024f99,2,12898,Tim Allen,1,/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg,52fe4284c3a36847f8024f4f,Writing,2,12891,Screenplay,Joss Whedon,/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg
2,862,16,Mr. Potato Head (voice),52fe4284c3a36847f8024f9d,2,7167,Don Rickles,2,/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg,52fe4284c3a36847f8024f55,Writing,2,7,Screenplay,Andrew Stanton,/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg
3,862,17,Slinky Dog (voice),52fe4284c3a36847f8024fa1,2,12899,Jim Varney,3,/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg,52fe4284c3a36847f8024f5b,Writing,2,12892,Screenplay,Joel Cohen,/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg
4,862,18,Rex (voice),52fe4284c3a36847f8024fa5,2,12900,Wallace Shawn,4,/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg,52fe4284c3a36847f8024f61,Writing,0,12893,Screenplay,Alec Sokolow,/v79vlRYi94BZUQnkkyznbGUZLjT.jpg

In [50]:
final_credits_dataset = new_df.copy()
final_credits_dataset.to_csv("credits_dataset_final.csv",index=False,compression="gzip")

In [4]:
df  = pd.read_csv("credits_unnested.csv", compression="gzip")
df.head(10)

,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,862,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","['Woody (voice)', 'Buzz Lightyear (voice)', 'M...","['52fe4284c3a36847f8024f95', '52fe4284c3a36847...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","['/pQFoyx7rp09CJTAb932F2g8Nlho.jpg', '/uX2xVf6...","['52fe4284c3a36847f8024f49', '52fe4284c3a36847...","['Directing', 'Writing', 'Writing', 'Writing',...","[2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, ...","[7879, 12891, 7, 12892, 12893, 12894, 12895, 1...","['Director', 'Screenplay', 'Screenplay', 'Scre...","['John Lasseter', 'Joss Whedon', 'Andrew Stant...","['/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg', '/dTiVsua..."
1,8844,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","['Alan Parrish', 'Samuel Alan Parrish / Van Pe...","['52fe44bfc3a36847f80a7c73', '52fe44bfc3a36847...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","['Robin Williams', 'Jonathan Hyde', 'Kirsten D...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","['/sojtJyIV3lkUeThD7A2oHNm8183.jpg', '/7il5D76...","['52fe44bfc3a36847f80a7cd1', '52fe44bfc3a36847...","['Production', 'Writing', 'Sound', 'Directing'...","[2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[511, 876, 1729, 4945, 4951, 4952, 8023, 9967,...","['Executive Producer', 'Screenplay', 'Original...","['Larry J. Franco', 'Jonathan Hensleigh', 'Jam...","[None, '/l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg', '/o..."
2,15602,"[2, 3, 4, 5, 6, 9, 10]","['Max Goldman', 'John Gustafson', 'Ariel Gusta...","['52fe466a9251416c75077a8d', '52fe466a9251416c...","[2, 2, 1, 1, 1, 2, 2]","[6837, 3151, 13567, 16757, 589, 16523, 7166]","['Walter Matthau', 'Jack Lemmon', 'Ann-Margret...","[0, 1, 2, 3, 4, 5, 6]","['/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg', '/chZmNRY...","['52fe466a9251416c75077a89', '52fe466b9251416c...","['Directing', 'Writing', 'Writing', 'Crew']","[2, 2, 2, 2]","[26502, 16837, 16837, 1551320]","['Director', 'Characters', 'Writer', 'Sound Re...","['Howard Deutch', 'Mark Steven Johnson', 'Mark...","['/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg', '/6trChNn..."
3,31357,"[1, 2, 3, 4, 5, 6, 8, 10, 20, 21]","[""Savannah 'Vannah' Jackson"", ""Bernadine 'Bern...","['52fe44779251416c91011aad', '52fe44779251416c...","[1, 1, 1, 1, 2, 2, 2, 2, 2, 2]","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","['Whitney Houston', 'Angela Bassett', 'Loretta...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","['/69ouDnXnmklYPr4sMJXWKYz81AL.jpg', '/tHkgSzh...","['52fe44779251416c91011acb', '52fe44779251416c...","['Directing', 'Writing', 'Production', 'Produc...","[2, 0, 0, 2, 1, 0, 0, 0, 2, 0]","[2178, 5144, 5144, 21968, 70592, 111118, 11111...","['Director', 'Screenplay', 'Producer', 'Produc...","['Forest Whitaker', 'Ronald Bass', 'Ronald Bas...","['/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg', None, Non..."
4,11862,"[1, 2, 3, 4, 13, 14, 15, 16, 17, 18, 19, 20]","['George Banks', 'Nina Banks', 'Franck Eggelho...","['52fe44959251416c75039eb9', '52fe44959251416c...","[2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1]","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","['Steve Martin', 'Diane Keaton', 'Martin Short...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]","['/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg', '/fzgUMnb...","['52fe44959251416c75039ed7', '52fe44959251416c...","['Sound', 'Camera', 'Writing', 'Production', '...","[2, 2, 1, 1, 2, 2, 2]","[37, 5506, 17698, 17698, 26160, 56106, 68755]","['Original Music Composer', 'Director of Photo...","['Alan Silvestri', 'Elliot Davis', 'Nancy Meye...","['/chEsfnDEtRmv1bfOaNAoVEzhCc6.jpg', None, '/n..."
5,949,"[25, 26, 27, 28, 29, 30, 31, 32, 33, 38, 35, 3...","['Lt. Vincent Hanna', 'Neil McCauley', 'Chris ...","['52fe4292c3a36847f80291f5', '52fe4292c3a36847...","[2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, ...","[1158, 380, 5576, 10127, 3197, 6200, 15851, 15...","['Al Pacino', 'Robert De Niro', 'Val Kilmer', ...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","['/ks7Ba8x9fJUlP9decBr6Dh5mThX.jpg', '/lvTSwUc...","['52fe4292c3a36847f802916d', '52fe4292c3a36847...","['Directing', 'Writing', 'Production', 'Produc...","[2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 2, 1, 1, 2, ...","[638, 638, 1254, 638, 5581, 11099, 15840, 1584...","['Director', 'Screenplay', 'Producer', 'Produc...","['Michael Mann', 'Michael Mann', 'Art Linson',...","['/nKmUpRpuQIsYubR7vIxVKhkbaTW.jpg', '/nKmUpRp..."
6,11860,"[1, 2, 3, 4, 11, 12, 13, 14, 15, 16, 17, 56, 5...","['Linus Larrabee', 'Sabrina Fairchild', 'David...","['52fe44959251416c75039d97', '52fe44959251416c...","[2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 0, 2, 1, 1, 1, ...","[3, 15887, 17141, 4301, 12957, 8937, 16554, 34...","['Harrison Ford', 'Julia Ormond', 'Greg Kinnea...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","['/7CcoVFTogQgex2kJkXKMe8qHZrC.jpg', '/GYnXYOv...","['52fe44959251416c75039da9', '52fe44959251416c...","['Directing', 'Writing', 'Production', 'Sound'...","[2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, ...","[2226, 70846, 2226, 491, 10640, 2997, 5490, 17...","['Director', 'Screenplay', 'Producer', 'Origin...","['Sydney Pollack', 'Barbara Benedek', 'Sydney ...","['/zxkoU2diKtvarV1Qk4z9He2lJj9.jpg', None, '/z..."
7,45325,"[2, 3, 4, 5, 6, 7, 11]","['Tom Sawyer', 'Huck Finn', 'Becky Thatcher', ...","['52fe46bdc3a36847f810f771', '52fe46bdc3a36847...","[2, 2, 1, 2, 1, 2, 1]","[53283, 51214, 38581, 8316, 87007, 57448, 102313]","['Jonathan Taylor Thomas', 'Brad Renfro', 'Rac...","[0, 1, 2, 3, 4, 5, 6]","['/1S8DpfNv6iiQRuKFPtb5u6sCQ5G.jpg', '/t97fjAt...","['52fe46bdc3a36847f810f797', '52fe46bdc3a36847...","['Writing', 'Writing', 'Directing', 'Writing']","[2, 2, 2, 2]","[2075, 7775, 18357, 72225]","['Screenplay', 'Screenplay', 'Director', 'Novel']","['David Loughery', 'Stephen Sommers', 'Peter H...","[None, '/50bI0PixdzrD5Mdygl4wrpxHCiH.jpg', '/w..."
8,9091,"[1, 2, 4, 15, 16, 17]","['Darren Francis Thomas McCord', 'Joshua Foss'...","['52fe44dbc3a36847f80ae0e3', '52fe44dbc3a36847...","[2, 2, 2, 2, 2, 1]","[15111, 6280, 8656, 10361, 12928, 79088]","['Jean-Claude Van Damme', 'Powers Boothe', 'Do...","[0, 1, 2, 3, 4, 5]","['/aqZ9RjL5j44HMlBMvTaawhHiGOH.jpg', '/3nNL6Av...","['52fe44dbc3a36847f80ae0f1', '52fe44dbc3a36847...","['Directing', 'Writing', 'Writing', 'Productio...","[2, 1, 2, 2, 0, 2, 2, 2, 2]","[37710, 53300, 56953, 56032, 56954, 53299, 450...","['Director', 'Screenplay', 'Screenplay', 'Prod...","['Peter Hyams', 'Karen Elise Baldwin', 'Gene Q...","['/dAuDsStGGlUESaaAYQf0GCE2JWo.jpg', None, Non..."
9,710,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","['James Bond', 'Alec Trevelyan', 'Natalya Fyod...","['52fe426ec3a36847f801e10d', '52fe426ec3a36847...","[2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, ...","[517, 48, 10695, 10696, 10671, 5309, 3757, 192...","['Pierce Brosnan', 'Sean Bean', 'Izabella Scor...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","['/1JXL0zrA26JjdoX8sqf57fJRDVM.jpg', '/iIxP2Iz...","['52fe426ec3a36847f801e14b', '52fe426ec3a36847...","['Directing', 'Writing', 'Writing', 'Writing',...","[2, 2, 2, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, ...","[10702, 9856, 10704, 10705, 10666, 10493, 996,...","['Director', 'Characters', 'Screenplay', 'Scre...","['Martin Campbell', 'Ian Fleming', 'Jeffrey Ca...","['/qhx0AySf8yH3kiHrinWknUJbr1y.jpg', '/3Pld5n7..."

In [6]:
# drop duplicates

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 45476 non-null  int64
 1   cast_id            43058 non-null  object
 2   character          43058 non-null  object
 3   credit_id          43058 non-null  object
 4   actor_gender       43058 non-null  object
 5   actor_id           43058 non-null  object
 6   actor_name         43058 non-null  object
 7   order              43058 non-null  object
 8   profile_path       43058 non-null  object
 9   crew_credit_id     44705 non-null  object
 10  crew_department    44705 non-null  object
 11  crew_gender        44705 non-null  object
 12  crew_id            44705 non-null  object
 13  crew_job           44705 non-null  object
 14  crew_name          44705 non-null  object
 15  crew_profile_path  44705 non-null  object
dtypes: int64(1), object(15)
memory usage: 5.6+ MB

In [7]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45439 entries, 0 to 45475
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 45439 non-null  int64
 1   cast_id            43025 non-null  object
 2   character          43025 non-null  object
 3   credit_id          43025 non-null  object
 4   actor_gender       43025 non-null  object
 5   actor_id           43025 non-null  object
 6   actor_name         43025 non-null  object
 7   order              43025 non-null  object
 8   profile_path       43025 non-null  object
 9   crew_credit_id     44668 non-null  object
 10  crew_department    44668 non-null  object
 11  crew_gender        44668 non-null  object
 12  crew_id            44668 non-null  object
 13  crew_job           44668 non-null  object
 14  crew_name          44668 non-null  object
 15  crew_profile_path  44668 non-null  object
dtypes: int64(1), object(15)
memory usage: 5.9+ MB

Aqui se hace la exportacion del data set final, llamado `credits_unnested_cleaned.csv`.

In [9]:
df.to_csv("credits_unnested_cleaned.csv",compression="gzip",index=False)

Se crearan dos archivos extras, uno para actores y otro para los miembros del crew , el `id` es el id de cada película

In [11]:
df.columns

Index(['id', 'cast_id', 'character', 'credit_id', 'actor_gender', 'actor_id',
       'actor_name', 'order', 'profile_path', 'crew_credit_id',
       'crew_department', 'crew_gender', 'crew_id', 'crew_job', 'crew_name',
       'crew_profile_path'],
      dtype='object')

Se aplica `explode()` para separar los datos.

In [12]:
df = pd.read_csv("credits_unnested_cleaned.csv",compression="gzip")
df.head(5)

,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,862,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","['Woody (voice)', 'Buzz Lightyear (voice)', 'M...","['52fe4284c3a36847f8024f95', '52fe4284c3a36847...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","['/pQFoyx7rp09CJTAb932F2g8Nlho.jpg', '/uX2xVf6...","['52fe4284c3a36847f8024f49', '52fe4284c3a36847...","['Directing', 'Writing', 'Writing', 'Writing',...","[2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, ...","[7879, 12891, 7, 12892, 12893, 12894, 12895, 1...","['Director', 'Screenplay', 'Screenplay', 'Scre...","['John Lasseter', 'Joss Whedon', 'Andrew Stant...","['/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg', '/dTiVsua..."
1,8844,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","['Alan Parrish', 'Samuel Alan Parrish / Van Pe...","['52fe44bfc3a36847f80a7c73', '52fe44bfc3a36847...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","['Robin Williams', 'Jonathan Hyde', 'Kirsten D...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","['/sojtJyIV3lkUeThD7A2oHNm8183.jpg', '/7il5D76...","['52fe44bfc3a36847f80a7cd1', '52fe44bfc3a36847...","['Production', 'Writing', 'Sound', 'Directing'...","[2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[511, 876, 1729, 4945, 4951, 4952, 8023, 9967,...","['Executive Producer', 'Screenplay', 'Original...","['Larry J. Franco', 'Jonathan Hensleigh', 'Jam...","[None, '/l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg', '/o..."
2,15602,"[2, 3, 4, 5, 6, 9, 10]","['Max Goldman', 'John Gustafson', 'Ariel Gusta...","['52fe466a9251416c75077a8d', '52fe466a9251416c...","[2, 2, 1, 1, 1, 2, 2]","[6837, 3151, 13567, 16757, 589, 16523, 7166]","['Walter Matthau', 'Jack Lemmon', 'Ann-Margret...","[0, 1, 2, 3, 4, 5, 6]","['/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg', '/chZmNRY...","['52fe466a9251416c75077a89', '52fe466b9251416c...","['Directing', 'Writing', 'Writing', 'Crew']","[2, 2, 2, 2]","[26502, 16837, 16837, 1551320]","['Director', 'Characters', 'Writer', 'Sound Re...","['Howard Deutch', 'Mark Steven Johnson', 'Mark...","['/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg', '/6trChNn..."
3,31357,"[1, 2, 3, 4, 5, 6, 8, 10, 20, 21]","[""Savannah 'Vannah' Jackson"", ""Bernadine 'Bern...","['52fe44779251416c91011aad', '52fe44779251416c...","[1, 1, 1, 1, 2, 2, 2, 2, 2, 2]","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","['Whitney Houston', 'Angela Bassett', 'Loretta...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","['/69ouDnXnmklYPr4sMJXWKYz81AL.jpg', '/tHkgSzh...","['52fe44779251416c91011acb', '52fe44779251416c...","['Directing', 'Writing', 'Production', 'Produc...","[2, 0, 0, 2, 1, 0, 0, 0, 2, 0]","[2178, 5144, 5144, 21968, 70592, 111118, 11111...","['Director', 'Screenplay', 'Producer', 'Produc...","['Forest Whitaker', 'Ronald Bass', 'Ronald Bas...","['/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg', None, Non..."
4,11862,"[1, 2, 3, 4, 13, 14, 15, 16, 17, 18, 19, 20]","['George Banks', 'Nina Banks', 'Franck Eggelho...","['52fe44959251416c75039eb9', '52fe44959251416c...","[2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1]","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","['Steve Martin', 'Diane Keaton', 'Martin Short...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]","['/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg', '/fzgUMnb...","['52fe44959251416c75039ed7', '52fe44959251416c...","['Sound', 'Camera', 'Writing', 'Production', '...","[2, 2, 1, 1, 2, 2, 2]","[37, 5506, 17698, 17698, 26160, 56106, 68755]","['Original Music Composer', 'Director of Photo...","['Alan Silvestri', 'Elliot Davis', 'Nancy Meye...","['/chEsfnDEtRmv1bfOaNAoVEzhCc6.jpg', None, '/n..."

In [19]:
# primero se convierten los datos con ast.list_eval
df = df.copy()
for item in df.columns:
  if item != 'id':
    df[item] = df[item].apply(lambda x: ast.literal_eval(x) if not pd.isna(x) else [])
df.head()

,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,862,"[14, 15, 16, 17, 18, 19, 20, 26, 22, 23, 24, 2...","[Woody (voice), Buzz Lightyear (voice), Mr. Po...","[52fe4284c3a36847f8024f95, 52fe4284c3a36847f80...","[2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2]","[31, 12898, 7167, 12899, 12900, 7907, 8873, 11...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[/pQFoyx7rp09CJTAb932F2g8Nlho.jpg, /uX2xVf6pMm...","[52fe4284c3a36847f8024f49, 52fe4284c3a36847f80...","[Directing, Writing, Writing, Writing, Writing...","[2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, ...","[7879, 12891, 7, 12892, 12893, 12894, 12895, 1...","[Director, Screenplay, Screenplay, Screenplay,...","[John Lasseter, Joss Whedon, Andrew Stanton, J...","[/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg, /dTiVsuaTVT..."
1,8844,"[1, 8, 2, 24, 10, 25, 26, 11, 14, 13, 31, 12, ...","[Alan Parrish, Samuel Alan Parrish / Van Pelt,...","[52fe44bfc3a36847f80a7c73, 52fe44bfc3a36847f80...","[2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 0, 0, ...","[2157, 8537, 205, 145151, 5149, 10739, 58563, ...","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[/sojtJyIV3lkUeThD7A2oHNm8183.jpg, /7il5D76vx6...","[52fe44bfc3a36847f80a7cd1, 52fe44bfc3a36847f80...","[Production, Writing, Sound, Directing, Editin...","[2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[511, 876, 1729, 4945, 4951, 4952, 8023, 9967,...","[Executive Producer, Screenplay, Original Musi...","[Larry J. Franco, Jonathan Hensleigh, James Ho...","[None, /l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg, /oLOt..."
2,15602,"[2, 3, 4, 5, 6, 9, 10]","[Max Goldman, John Gustafson, Ariel Gustafson,...","[52fe466a9251416c75077a8d, 52fe466a9251416c750...","[2, 2, 1, 1, 1, 2, 2]","[6837, 3151, 13567, 16757, 589, 16523, 7166]","[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...","[0, 1, 2, 3, 4, 5, 6]","[/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg, /chZmNRYMtq...","[52fe466a9251416c75077a89, 52fe466b9251416c750...","[Directing, Writing, Writing, Crew]","[2, 2, 2, 2]","[26502, 16837, 16837, 1551320]","[Director, Characters, Writer, Sound Recordist]","[Howard Deutch, Mark Steven Johnson, Mark Stev...","[/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg, /6trChNn3o2..."
3,31357,"[1, 2, 3, 4, 5, 6, 8, 10, 20, 21]","[Savannah 'Vannah' Jackson, Bernadine 'Bernie'...","[52fe44779251416c91011aad, 52fe44779251416c910...","[1, 1, 1, 1, 2, 2, 2, 2, 2, 2]","[8851, 9780, 18284, 51359, 66804, 352, 87118, ...","[Whitney Houston, Angela Bassett, Loretta Devi...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[/69ouDnXnmklYPr4sMJXWKYz81AL.jpg, /tHkgSzhEuJ...","[52fe44779251416c91011acb, 52fe44779251416c910...","[Directing, Writing, Production, Production, P...","[2, 0, 0, 2, 1, 0, 0, 0, 2, 0]","[2178, 5144, 5144, 21968, 70592, 111118, 11111...","[Director, Screenplay, Producer, Producer, Pro...","[Forest Whitaker, Ronald Bass, Ronald Bass, Ez...","[/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg, None, None,..."
4,11862,"[1, 2, 3, 4, 13, 14, 15, 16, 17, 18, 19, 20]","[George Banks, Nina Banks, Franck Eggelhoffer,...","[52fe44959251416c75039eb9, 52fe44959251416c750...","[2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1]","[67773, 3092, 519, 70696, 59222, 18793, 14592,...","[Steve Martin, Diane Keaton, Martin Short, Kim...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]","[/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg, /fzgUMnbOkx...","[52fe44959251416c75039ed7, 52fe44959251416c750...","[Sound, Camera, Writing, Production, Writing, ...","[2, 2, 1, 1, 2, 2, 2]","[37, 5506, 17698, 17698, 26160, 56106, 68755]","[Original Music Composer, Director of Photogra...","[Alan Silvestri, Elliot Davis, Nancy Meyers, N...","[/chEsfnDEtRmv1bfOaNAoVEzhCc6.jpg, None, /nMPH..."

In [20]:
cast_id = df[["id","cast_id"]].explode("cast_id").reset_index(drop=True)
character= df[["id","character"]].explode("character").reset_index(drop=True)
credit_id= df[["id","credit_id"]].explode("credit_id").reset_index(drop=True)
actor_gender= df[["id","actor_gender"]].explode("actor_gender").reset_index(drop=True)
actor_id= df[["id","actor_id"]].explode("actor_id").reset_index(drop=True)
actor_name= df[["id","actor_name"]].explode("actor_name").reset_index(drop=True)
order= df[["id","order"]].explode("order").reset_index(drop=True)
profile_path= df[["id","profile_path"]].explode("profile_path").reset_index(drop=True)
crew_credit_id= df[["id","crew_credit_id"]].explode("crew_credit_id").reset_index(drop=True)
crew_department= df[["id","crew_department"]].explode("crew_department").reset_index(drop=True)
crew_gender= df[["id","crew_gender"]].explode("crew_gender").reset_index(drop=True)
crew_id= df[["id","crew_id"]].explode("crew_id").reset_index(drop=True)
crew_job= df[["id","crew_job"]].explode("crew_job").reset_index(drop=True)
crew_name= df[["id","crew_name"]].explode("crew_name").reset_index(drop=True)
crew_profile_path= df[["id","crew_profile_path"]].explode("crew_profile_path").reset_index(drop=True)

In [21]:
actors_df = cast_id
actors_df['character'] = character["character"]
actors_df['credit_id'] = credit_id["credit_id"]
actors_df['actor_gender'] = actor_gender["actor_gender"]
actors_df['actor_id'] = actor_id["actor_id"]
actors_df['actor_name'] = actor_name["actor_name"]
actors_df['order'] = order["order"]
actors_df['profile_path'] = profile_path["profile_path"]

crew_df = crew_credit_id
crew_df['crew_department'] = crew_department["crew_department"]
crew_df['crew_gender'] = crew_gender["crew_gender"]
crew_df['crew_id'] = crew_id["crew_id"]
crew_df['crew_job'] = crew_job["crew_job"]
crew_df['crew_name'] = crew_name["crew_name"]
crew_df['crew_profile_path'] = crew_profile_path["crew_profile_path"]
crew_df.head()

,id,crew_credit_id,crew_department,crew_gender,crew_id,crew_job,crew_name,crew_profile_path
0,862,52fe4284c3a36847f8024f49,Directing,2,7879,Director,John Lasseter,/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg
1,862,52fe4284c3a36847f8024f4f,Writing,2,12891,Screenplay,Joss Whedon,/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg
2,862,52fe4284c3a36847f8024f55,Writing,2,7,Screenplay,Andrew Stanton,/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg
3,862,52fe4284c3a36847f8024f5b,Writing,2,12892,Screenplay,Joel Cohen,/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg
4,862,52fe4284c3a36847f8024f61,Writing,0,12893,Screenplay,Alec Sokolow,/v79vlRYi94BZUQnkkyznbGUZLjT.jpg

In [22]:
actors_df.head()

,id,cast_id,character,credit_id,actor_gender,actor_id,actor_name,order,profile_path
0,862,14,Woody (voice),52fe4284c3a36847f8024f95,2,31,Tom Hanks,0,/pQFoyx7rp09CJTAb932F2g8Nlho.jpg
1,862,15,Buzz Lightyear (voice),52fe4284c3a36847f8024f99,2,12898,Tim Allen,1,/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg
2,862,16,Mr. Potato Head (voice),52fe4284c3a36847f8024f9d,2,7167,Don Rickles,2,/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg
3,862,17,Slinky Dog (voice),52fe4284c3a36847f8024fa1,2,12899,Jim Varney,3,/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg
4,862,18,Rex (voice),52fe4284c3a36847f8024fa5,2,12900,Wallace Shawn,4,/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg

Se exportan los csv de actores y miembros del crew

In [35]:
actors_df.drop_duplicates(inplace=True)

In [31]:
crew_df.drop_duplicates(inplace=True)

In [37]:
actors_df.to_csv("actors.csv",index=False,compression="gzip")
crew_df.to_csv("crew.csv",index=False,compression="gzip")